channels:
  - conda-forge
dependencies:
  - llvm-openmp
  - django=4.1
  - matplotlib=3.5.3
  - pandas=1.4.4
  - pillow=9.2.0
  - pip>=22
  - python=3.10
  - python-dotenv=1.0.0
  - scipy=1.9.1
  - tensorflow=2.9.1
  - traitlets=5.3.0
  - seaborn=0.11.2
  - zstd=1.5.2
  - scikit-learn=1.2.0
  - pytesseract=0.3.10
  - tesseract=5.3.0
  - pip:
    - canvasapi==2.2.0
    - crispy-bootstrap5==0.6
    - django-countries==7.3.2
    - django-crispy-forms==1.14.0
    - opencv-python-headless==4.7.0.72
    - pymupdf==1.21.1
    - "--editable=git+https://github.com/IonMich/autocanvas.git@main#egg=autocanvas"
name: django-ta
